-- ==========================================
-- MIGRACIÓN OBSOLETA — INACTIVA
--
-- Esta migración quedó obsoleta y fue reemplazada por
-- 20260915000741_webhook_nueva_solicitud.sql, que implementa el webhook de
-- nueva solicitud con la extensión pg_net.
--
-- El contenido original creaba un trigger basado en
-- supabase_functions.http_request (esquema de Database Webhooks que solo
-- existe si se activa ese panel manualmente en el dashboard). Eso hacía que
-- 'supabase db push' fallara en el proyecto de la nube antes de poder activar
-- la feature.
--
-- Se sustituye por un no-op (solo comentarios, cero sentencias SQL) para no
-- romper el historial de migraciones: el archivo se conserva, pero la base
-- recibe una migración vacía. El trigger viejo, de existir, se elimina de
-- manera segura en la migración 20260915000741 con DROP TRIGGER IF EXISTS.
--
-- No eliminar este archivo: rompería el historial de migraciones ya aplicadas.
-- ==========================================